<a href="https://colab.research.google.com/github/mradulpandya/Data_Analysis/blob/main/Different_Data_Analysis_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Merge

In [14]:
dframe1 = DataFrame({'key':['x','y','z','a','b','c'],'data_Set_1':np.arange(6)})

In [15]:
dframe1

key  data_Set_1
0   x           0
1   y           1
2   z           2
3   a           3
4   b           4
5   c           5

In [16]:
dframe2 = DataFrame({'key':['x','y',' r'],'data_Set_2':[1,2,3]})

In [17]:
dframe2

key  data_Set_2
0   x           1
1   y           2
2   r           3

In [18]:
pd.merge(dframe1,dframe2)

key  data_Set_1  data_Set_2
0   x           0           1
1   y           1           2

In [19]:
pd.merge(dframe1,dframe2, on='key', how='left')

key  data_Set_1  data_Set_2
0   x           0         1.0
1   y           1         2.0
2   z           2         NaN
3   a           3         NaN
4   b           4         NaN
5   c           5         NaN

In [20]:
pd.merge(dframe1,dframe2, on='key', how='right')

key  data_Set_1  data_Set_2
0   x         0.0           1
1   y         1.0           2
2   r         NaN           3

In [21]:
pd.merge(dframe1,dframe2, on='key', how='outer')

key  data_Set_1  data_Set_2
0   x         0.0         1.0
1   y         1.0         2.0
2   z         2.0         NaN
3   a         3.0         NaN
4   b         4.0         NaN
5   c         5.0         NaN
6   r         NaN         3.0

In [28]:
dframe3 = DataFrame({'key':['x','x','y','y','z','z'],'data_Set_3':range(6)})

In [31]:
dframe3

key  data_Set_3
0   x           0
1   x           1
2   y           2
3   y           3
4   z           4
5   z           5

In [34]:
dframe4 = DataFrame({'key':['y','y','x','x','z'],'data_Set_4':range(5)})

In [35]:
dframe4

key  data_Set_4
0   y           0
1   y           1
2   x           2
3   x           3
4   z           4

In [36]:
pd.merge(dframe3,dframe4)

key  data_Set_3  data_Set_4
0   x           0           2
1   x           0           3
2   x           1           2
3   x           1           3
4   y           2           0
5   y           2           1
6   y           3           0
7   y           3           1
8   z           4           4
9   z           5           4

In [47]:
dframe5 = DataFrame({'key1':['ab','cd','ef'],'key2':['gh','ij','jk'], 'data_Set_5':[10,20,30]})

In [48]:
dframe5

key1 key2  data_Set_5
0   ab   gh          10
1   cd   ij          20
2   ef   jk          30

In [49]:
dframe6 = DataFrame({'key1':['ab','cd','ef','ab'],'key2':['gh','ij','jk','ij'], 'data_Set_6':[40,50,60,70]})

In [46]:
dframe6

key  data_Set_6
0  gh          40
1  ij          50
2  jk          60
3  ij          70

In [52]:
pd.merge(dframe5,dframe6, on=['key1','key2'], how='outer')

key1 key2  data_Set_5  data_Set_6
0   ab   gh        10.0          40
1   cd   ij        20.0          50
2   ef   jk        30.0          60
3   ab   ij         NaN          70

In [55]:
pd.merge(dframe5,dframe6, on='key1', suffixes=('_lefty','_righty'))

key1 key2_lefty  data_Set_5 key2_righty  data_Set_6
0   ab         gh          10          gh          40
1   ab         gh          10          ij          70
2   cd         ij          20          ij          50
3   ef         jk          30          jk          60

# Merge on Index

In [56]:
dframe_left = DataFrame({'key':['x','y','z','x','y'], 'data':range(5)})

In [57]:
dframe_left

key  data
0   x     0
1   y     1
2   z     2
3   x     3
4   y     4

In [59]:
dframe_right = DataFrame({'group_data':[10,20]}, index=['x','y'])

In [61]:
dframe_right

group_data
x          10
y          20

In [71]:
pd.merge(dframe_left, dframe_right, left_on='key', right_index=True)

key  data  group_data
0   x     0          10
3   x     3          10
1   y     1          20
4   y     4          20

In [72]:
dframe_lest_hr = DataFrame({'key1':['ab','ab,','ab','cd','cd'],'key2':[10,20,30,20,30], 'data_Set_5':range(5)})

In [73]:
dframe_lest_hr

key1  key2  data_Set_5
0   ab    10           0
1  ab,    20           1
2   ab    30           2
3   cd    20           3
4   cd    30           4

In [76]:
dframe_right_hr = DataFrame(np.arange(10).reshape(5,2), index=[['cd','cd','ab','ab','cd'],[20,10,10,10,20]], columns=['col1','col2'])

In [77]:
dframe_right_hr

col1  col2
cd 20     0     1
   10     2     3
ab 10     4     5
   10     6     7
cd 20     8     9

In [78]:
pd.merge(dframe_lest_hr,dframe_right_hr, left_on=['key1','key2'], right_index=True)

key1  key2  data_Set_5  col1  col2
0   ab    10           0     4     5
0   ab    10           0     6     7
3   cd    20           3     0     1
3   cd    20           3     8     9

# Concatenate

In [85]:
arr1 = np.arange(9).reshape(3,3)

In [86]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [88]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
ser1 = Series([0,1,2],index=['x','y','z'])

In [96]:
ser1

x    0
y    1
z    2
dtype: int64

In [97]:
ser2 = Series([3,4],index=['y','z'])

In [98]:
pd.concat([ser1,ser2])

x    0
y    1
z    2
y    3
z    4
dtype: int64

In [99]:
pd.concat([ser1,ser2], axis=1)

0    1
x  0  NaN
y  1  3.0
z  2  4.0

In [101]:
pd.concat([ser1,ser2], keys=['cat1','cat2'])

cat1  x    0
      y    1
      z    2
cat2  y    3
      z    4
dtype: int64

In [102]:
dframe1 = DataFrame(np.random.randn(3,3), columns=['x','y','z'])

In [104]:
dframe1

x         y         z
0  1.325799 -0.926243 -0.920444
1 -1.961822 -0.684057 -0.913454
2 -1.103186  0.906174 -0.283436
3 -0.109898 -1.198636 -0.686956

In [103]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['a','b','z'])

In [105]:
dframe2

a         b         z
0  0.007455  1.073840 -1.022249
1 -0.350831 -1.375166 -0.265834
2  0.016211  0.448294 -1.008803

In [106]:
pd.concat([dframe1,dframe2])

x         y         z         a         b
0  1.325799 -0.926243 -0.920444       NaN       NaN
1 -1.961822 -0.684057 -0.913454       NaN       NaN
2 -1.103186  0.906174 -0.283436       NaN       NaN
3 -0.109898 -1.198636 -0.686956       NaN       NaN
0       NaN       NaN -1.022249  0.007455  1.073840
1       NaN       NaN -0.265834 -0.350831 -1.375166
2       NaN       NaN -1.008803  0.016211  0.448294

In [107]:
pd.concat([dframe1,dframe2], ignore_index=True)

x         y         z         a         b
0  1.325799 -0.926243 -0.920444       NaN       NaN
1 -1.961822 -0.684057 -0.913454       NaN       NaN
2 -1.103186  0.906174 -0.283436       NaN       NaN
3 -0.109898 -1.198636 -0.686956       NaN       NaN
4       NaN       NaN -1.022249  0.007455  1.073840
5       NaN       NaN -0.265834 -0.350831 -1.375166
6       NaN       NaN -1.008803  0.016211  0.448294

# Combine DataFrame

In [109]:
ser1 = Series([2,np.nan,4,np.nan,6,np.nan], index=['a','b','c','d','e','f'])

In [110]:
ser1

a    2.0
b    NaN
c    4.0
d    NaN
e    6.0
f    NaN
dtype: float64

In [113]:
ser2 = Series(np.arange(len(ser1)), dtype=np.float64, index=['a','b','c','d','e','f'])

In [114]:
ser2

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
dtype: float64

In [116]:
Series(np.where(pd.isnull(ser1),ser2,ser1),index=ser1.index)

a    2.0
b    1.0
c    4.0
d    3.0
e    6.0
f    5.0
dtype: float64

In [117]:
#shortcut method
ser1.combine_first(ser2)

a    2.0
b    1.0
c    4.0
d    3.0
e    6.0
f    5.0
dtype: float64

In [121]:
dframe_odds = DataFrame({'x':[1,np.nan,3,np.nan],'y':[4,5,np.nan,np.nan],'z':[np.nan,6,7,np.nan]})

In [123]:
dframe_odds

x    y    z
0  1.0  4.0  NaN
1  NaN  5.0  6.0
2  3.0  NaN  7.0
3  NaN  NaN  NaN

In [127]:
dframe_even = DataFrame({'x':[4,5,np.nan,6],'y':[np.nan,np.nan,7,8],'z':[99,np.nan,np.nan,10]})

In [128]:
dframe_even

x    y     z
0  4.0  NaN  99.0
1  5.0  NaN   NaN
2  NaN  7.0   NaN
3  6.0  8.0  10.0

In [129]:
dframe_odds.combine_first(dframe_even)
                          

x    y     z
0  1.0  4.0  99.0
1  5.0  5.0   6.0
2  3.0  7.0   7.0
3  6.0  8.0  10.0